title: Веб-страница Wolodyx
email: wolodyx@yandex.ru
description: >- # this means to ignore newlines until "baseurl:"
  Персональная страница Wolodyx.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: wolodyx 

# Build settings
markdown: CommonMarkGhPages # https://github.com/github/jekyll-commonmark-ghpages
theme: minima
#remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

yandex_metrika: 92989892

header_pages:
  - about-en.md
